
version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d myapp"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    image: yourdockerhubusername/python-backend:latest  # Replace with your DockerHub username
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/myapp
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: yourdockerhubusername/python-frontend:latest  # Replace with your DockerHub username
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000/api/data
    ports:
      - "8080:80"

  logger:
    image: yourdockerhubusername/python-logger:latest  # Replace with your DockerHub username
    depends_on:
      - backend
    volumes:
      - ./logs:/app/logs
    environment:
      - BACKEND_URL=http://backend:5000

volumes:
  postgres_data: